<?php

/**
 * ============================================================================
 * IQArchive v2 — User Model
 * ============================================================================
 * File: app/Models/User.php
 * Responsibility: Institutional user entity with college multi-tenant association.
 * Architecture: Model Layer (3NF Schema)
 * Security Context: Multi-tenant college_id foreign key; role-scoped permissions.
 * ============================================================================
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'college_id',
        'name',
        'email',
        'google_id',
        'avatar_url',
        'status',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'college_id' => 'integer',
        ];
    }

    /**
     * College associated with this user (for College Deans and Faculty; null for IQA/BU Exec/SysAdmin).
     */
    public function college(): BelongsTo
    {
        return $this->belongsTo(College::class);
    }

    /**
     * Roles assigned to this user through user_roles table.
     */
    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(Role::class, 'user_roles')->withTimestamps();
    }

    /**
     * Direct user role junction records.
     */
    public function userRoles(): HasMany
    {
        return $this->hasMany(UserRole::class);
    }

    /**
     * Primary role name accessor for Inertia/frontend compatibility.
     */
    public function getRoleAttribute(): ?string
    {
        return $this->roles->first()?->name;
    }

    /**
     * Check if user has a specific role name or any role within an array.
     */
    public function hasRole(string|array $roleName): bool
    {
        if (is_array($roleName)) {
            return $this->roles->whereIn('name', $roleName)->isNotEmpty();
        }

        return $this->roles->contains('name', $roleName);
    }

    /**
     * Documents uploaded by this user.
     */
    public function documents(): HasMany
    {
        return $this->hasMany(Document::class, 'user_id');
    }

    /**
     * Audit log entries generated by this user.
     */
    public function auditLogs(): HasMany
    {
        return $this->hasMany(AuditLog::class, 'user_id');
    }

    /**
     * In-app notifications for this user.
     */
    public function notifications(): HasMany
    {
        return $this->hasMany(Notification::class, 'user_id');
    }

    /**
     * Task force memberships.
     */
    public function taskForceMembers(): HasMany
    {
        return $this->hasMany(TaskForceMember::class, 'user_id');
    }

    /**
     * Document reviews conducted by this user.
     */
    public function documentReviews(): HasMany
    {
        return $this->hasMany(DocumentReview::class, 'user_id');
    }
}
